name: Create a Release.

on:
  push:
    tags:
    - '*'

jobs:

  CreateRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge staging -> release
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: staging
        target_branch: release
        github_token: ${{ github.token }}
